source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'PhotoDemo' do

  #自动布局
  pod 'Masonry'
  
  #第三方相册查看选择器
  pod 'TZImagePickerController'
  
end

